### PR TITLE
Swap [Contest]

### PR DESCRIPTION
**Pull request by protoshadowmaker**
Release APK:
[rc-yauhendev.apk.zip](https://github.com/tonkeeper/android/files/15476929/rc-yauhendev.apk.zip)
P.s. include dev branch changes

### CODE REVIEW

**Comment by Khaledd-22** [comment]
رئيسي

**Comment by protoshadowmaker** [comment]
Not actual yet

**Comment by Nazgolakhondi1388** [comment]
https://github.com/tonkeeper/android/pull/10

**Comment by Nazgolakhondi1388** [comment]
9🤩🤩🤩🤩🤩🤩

**Pull request closed without merging**
